### ISSUE TITLE
执行后run.php  提示    ERROR   swReactorEpoll_del(:157): epoll remove fd[10#0] failed. Error: No such file or directory[2].

### ISSUE THREAD

**Issue by colloq168** [CatsSystem/CatApiApp#1]
执行后run.php  提示    ERROR   swReactorEpoll_del(:157): epoll remove fd[10#0] failed. Error: No such file or directory[2].

**Comment by LinkedDestiny** [comment]
这个是Swoole底层的报错信息，通常不是代码逻辑问题，而是由于网络因素，某些fd在已经被移除的情况下二次删除导致的
